### ISSUE TITLE
Possible to add license? 

### ISSUE THREAD

**Issue by smeijer** [vvo/sourcekarma#2]
Would it be possible to add a license file?

**Comment by vvo** [comment]
Sure, may I ask why? (I'll do it, just curious!)

**Comment by vvo** [comment]
Done: https://github.com/vvo/sourcekarma/blob/main/LICENSE

**Comment by smeijer** [comment]
Thanks. No special reason. I think most of us just prefer any license over no license at all. At least that way we know what we can, and cannot do with the code.
