### ISSUE TITLE
Error occurred during fetch request

### ISSUE THREAD

**Issue by PierreRambaud** [vvo/sourcekarma#7]
Hi,
I want to try your tool but, unfortunately, with my account, I can fetch anything :sweat_smile: 

![image](https://user-images.githubusercontent.com/1462701/110602508-5fee8500-8186-11eb-9708-7813ed2f74b3.png)

Don't hesitate if you need specific information or anything else

**Comment by PierreRambaud** [comment]
haha it's funny, as someone suggests, maybe use cursors to fetch data, it will help for people with a lot of comments ^^

**Comment by vvo** [comment]
I already use cursors because that's the default pagination strategy for GitHub GraphQL API.

I don't see how this can help further, what do you mean?

**Comment by PierreRambaud** [comment]
Even if you use cursor, you should return the requests as fast as possible.
https://github.com/vvo/sourcekarma/blob/47d3c85ecb74393f29f387dd502b3a6f1a6b465b/pages/%5Blogin%5D/index.js#L661
You're doing a recursive request.

Maybe calling this method one, returns the result in the front, then rerun the next request, and continue until the end, data will be populated as soon as possible, but you should be able to bypass the Vercel timeout.
